# USAERO – EDA bản gọn: nhanh, chạy được nhiều năm, dễ học

**Ba ý tưởng chính (đọc xong là hiểu cả notebook):**
1. **Tính một lần, cộng lại nhiều lần.** Mỗi tháng chỉ đọc dữ liệu thô một lần, lưu các cột *cộng được* (đếm, tổng). Ngày, tháng, năm, mùa vụ chỉ là phép cộng các bảng nhỏ này; tỷ lệ luôn tính lại từ tổng.
2. **Box-plot chính xác từ biểu đồ tần suất.** Phân vị không cộng được, nhưng "số chuyến có delay = v phút" thì cộng được. Nhờ đó box-plot mọi mức không cần quét lại dữ liệu thô.
3. **Null có ngữ nghĩa.** `ARR_DELAY`/`DEP_DELAY` null = hủy/chuyển hướng (không điền 0). Cột nguyên nhân trễ null = không trễ ≥15' (điền 0).

Chạy lần lượt từ trên xuống. Build có thể ngắt và chạy lại: tháng đã xong sẽ được bỏ qua.

### 1. Môi trường, cấu hình, quy ước chỉ số

In [1]:
import os, sys, glob, re, time, json, io, contextlib, datetime as dt
if os.path.isdir("/opt/spark"):
    os.environ.setdefault("SPARK_HOME", "/opt/spark")
try:
    import pyspark
except ModuleNotFoundError:
    sys.path.insert(0, "/opt/spark/python")
    sys.path.extend(glob.glob("/opt/spark/python/lib/py4j-*-src.zip"))
    import pyspark
from pyspark.sql import SparkSession, Window, functions as F, types as T
from pyspark import StorageLevel

# ── Đường dẫn ──
PROCESSED    = os.environ.get("AERO_PROCESSED", "/aero/processed")       # đầu ra của 06_batch_process_all.py
ANALYTICS    = os.environ.get("AERO_ANALYTICS", "/aero/analytics/eda")   # nơi ghi kết quả phân tích
HDFS_URI     = os.environ.get("AERO_HDFS", "hdfs://namenode:9000")
WAREHOUSE    = os.environ.get("AERO_WAREHOUSE", (HDFS_URI + "/aero/warehouse") if HDFS_URI else "/tmp/aero_warehouse")
EVIDENCE_DIR = os.environ.get("AERO_EVIDENCE", "./evidence")

def month_range(start, end):
    (y, m), (ey, em), out = start, end, []
    while (y, m) <= (ey, em):
        out.append((y, m)); m += 1
        if m > 12: y, m = y + 1, 1
    return out

MONTHS = month_range((2022, 1), (2026, 3))       # toàn bộ 51 tháng. Muốn chạy thử: month_range((2022, 1), (2022, 3))
_env = os.environ.get("AERO_MONTHS")
if _env:
    _ym = lambda s: tuple(int(x) for x in s.split("-"))
    MONTHS = [_ym(s) for s in _env.split(",")] if "," in _env else month_range(*[_ym(s) for s in _env.split(":")])
FORCE_REBUILD = False                            # False: tháng nào đã build rồi thì bỏ qua (chạy lại được sau khi bị ngắt)

# ── Quy ước chỉ số (định nghĩa ở MỘT chỗ) ──
LATE_MIN    = 15      # chuyến "trễ" khi ARR_DELAY >= 15 phút (chuẩn DOT/BTS)
MIN_FLIGHTS = 200     # nhóm nhỏ hơn bị loại khi xếp hạng
MIN_BOX_N   = 30      # box-plot của nhóm nhỏ hơn được gắn reliable=False
W_DELAY, W_SEVERE, W_CANCEL, W_DIVERT = 0.50, 0.20, 0.25, 0.05   # trọng số reliability_score (chỉ số tự định nghĩa)

spark = (SparkSession.builder.master("local[2]").appName("usaero-eda")
         .config("spark.driver.memory", "2g")
         .config("spark.sql.shuffle.partitions", os.environ.get("AERO_SHUFFLE", "8"))
         .config("spark.sql.adaptive.enabled", "true").config("spark.sql.session.timeZone", "UTC")
         .config("spark.sql.sources.partitionOverwriteMode", "dynamic").config("spark.sql.warehouse.dir", WAREHOUSE))
if HDFS_URI:
    spark = spark.config("spark.hadoop.fs.defaultFS", HDFS_URI)
spark = spark.getOrCreate()
spark.sparkContext.setLogLevel("WARN")
print("pyspark", pyspark.__version__, "| Spark", spark.version, "| python", sys.version.split()[0],
      f"| {len(MONTHS)} tháng: {MONTHS[0][0]}-{MONTHS[0][1]:02d} → {MONTHS[-1][0]}-{MONTHS[-1][1]:02d}")

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/10/28 08:27:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

pyspark 3.5.9 | Spark 3.5.3 | python 3.8.10 | 51 tháng: 2022-01 → 2026-03

### 2. Nạp dữ liệu theo tháng và chuẩn hóa

In [2]:
# ── Nạp dữ liệu theo tháng: chỉ đọc đúng thư mục year=/month= cần (partition pruning) ──
def _hpath(p):
    path = spark._jvm.org.apache.hadoop.fs.Path(p)
    return path, path.getFileSystem(spark._jsc.hadoopConfiguration())

def month_dir(y, m):
    for name in (f"month={m:02d}", f"month={m}"):
        p = f"{PROCESSED}/year={y}/{name}"
        path, fs = _hpath(p)
        if fs.exists(path): return p
    return None

def load_months(months, verbose=True):
    found = [p for p in (month_dir(y, m) for y, m in months) if p]
    miss = [f"{y}-{m:02d}" for y, m in months if not month_dir(y, m)]
    if miss and verbose: print(f"⚠ Thiếu {len(miss)} tháng (bỏ qua): {', '.join(miss)}")
    if not found: raise FileNotFoundError(f"Không có partition nào dưới {PROCESSED}")
    return spark.read.option("basePath", PROCESSED).parquet(*found)

# ── Tên cột có thể khác nhau: khai báo các tên ứng viên cho mỗi trường logic ──
COLS = {"fl_date": ["FL_DATE", "FlightDate"], "carrier": ["OP_UNIQUE_CARRIER", "OP_CARRIER", "REPORTING_AIRLINE", "CARRIER"],
        "origin": ["ORIGIN"], "dest": ["DEST"], "tail": ["TAIL_NUM"], "crs_dep_time": ["CRS_DEP_TIME"],
        "dep_delay": ["DEP_DELAY"], "arr_delay": ["ARR_DELAY"], "cancelled": ["CANCELLED"], "diverted": ["DIVERTED"],
        "cancel_code": ["CANCELLATION_CODE"], "d_carrier": ["CARRIER_DELAY"], "d_weather": ["WEATHER_DELAY"],
        "d_nas": ["NAS_DELAY"], "d_security": ["SECURITY_DELAY"], "d_late_aircraft": ["LATE_AIRCRAFT_DELAY"]}
REQUIRED = ["fl_date", "carrier", "origin", "dest", "dep_delay", "arr_delay", "cancelled"]
CAUSES = ["carrier", "weather", "nas", "security", "late_aircraft"]
COLMAP = {}

def prepare(raw):
    """Chuẩn hóa MỘT lần ở MỘT chỗ. Hai quy tắc null quan trọng nhất:
       • ARR_DELAY/DEP_DELAY null = chuyến hủy/chuyển hướng → KHÔNG điền 0 (nếu điền, chuyến hủy bị tính là đúng giờ).
       • Cột nguyên nhân trễ null = chuyến không trễ ≥15' → điền 0."""
    global COLMAP
    low = {c.lower(): c for c in raw.columns}
    m = {k: next((low[c.lower()] for c in cands if c.lower() in low), None) for k, cands in COLS.items()}
    miss = [k for k in REQUIRED if m[k] is None]
    if miss: raise ValueError(f"Thiếu cột bắt buộc {miss}. Cột hiện có: {raw.columns}")
    COLMAP = m
    col = lambda k, t="double": F.col(f"`{m[k]}`").cast(t) if m[k] else F.lit(None).cast(t)
    d = raw.select(
        F.to_date(F.col(f"`{m['fl_date']}`")).alias("fl_date"),
        *[F.col(f"`{m[k]}`").cast("string").alias(k) for k in ("carrier", "origin", "dest")],
        col("tail", "string").alias("tail"), col("crs_dep_time", "int").alias("crs_dep_time"),
        col("dep_delay").alias("dep_delay"), col("arr_delay").alias("arr_delay"),
        F.coalesce(col("cancelled", "int"), F.lit(0)).alias("cancelled"),
        F.coalesce(col("diverted", "int"), F.lit(0)).alias("diverted"),
        col("cancel_code", "string").alias("cancel_code"),
        *[F.coalesce(col(f"d_{k}"), F.lit(0.0)).alias(f"d_{k}") for k in CAUSES],
    ).where(F.col("fl_date").isNotNull())
    return (d.withColumn("year", F.year("fl_date")).withColumn("month", F.month("fl_date")).withColumn("day", F.dayofmonth("fl_date"))
             .withColumn("dep_hour", (F.floor(F.col("crs_dep_time") / 100) % 24).cast("int"))
             .withColumn("dep_min", (F.col("crs_dep_time") % 100).cast("int"))
             .withColumn("operated", ((F.col("cancelled") == 0) & (F.col("diverted") == 0)).cast("int"))
             .withColumn("arr_delay_ok", F.when(F.col("operated") == 1, F.col("arr_delay")))     # null nếu hủy/chuyển hướng
             .withColumn("dep_delay_ok", F.when(F.col("cancelled") == 0, F.col("dep_delay")))
             .withColumn("air_gain", F.when(F.col("arr_delay_ok").isNotNull() & F.col("dep_delay_ok").isNotNull(),
                                            F.col("dep_delay_ok") - F.col("arr_delay_ok"))))     # >0: bù được giờ trên không

# ── Bảng tra nhỏ (dùng cho broadcast join) ──
CARRIERS = {"AA": "American", "DL": "Delta", "UA": "United", "WN": "Southwest", "B6": "JetBlue", "AS": "Alaska", "NK": "Spirit",
            "F9": "Frontier", "G4": "Allegiant", "HA": "Hawaiian", "YX": "Republic", "OO": "SkyWest", "MQ": "Envoy", "9E": "Endeavor",
            "OH": "PSA", "YV": "Mesa", "QX": "Horizon", "ZW": "Air Wisconsin", "C5": "CommutAir", "G7": "GoJet", "CP": "Compass",
            "SY": "Sun Country", "MX": "Breeze", "9K": "Cape Air"}
def carrier_lookup(): return spark.createDataFrame(list(CARRIERS.items()), ["carrier", "carrier_name"])

def _nth_weekday(y, m, weekday, n):                 # weekday 0=Thứ hai; n>0: thứ n; n=-1: thứ cuối cùng
    if n > 0:
        d = dt.date(y, m, 1); return d + dt.timedelta(days=(weekday - d.weekday()) % 7 + 7 * (n - 1))
    d = dt.date(y + (m == 12), (m % 12) + 1, 1) - dt.timedelta(days=1)
    return d - dt.timedelta(days=(d.weekday() - weekday) % 7)

def holiday_df(years=range(2021, 2028), window=3):
    """Ngày trong ±3 ngày quanh 6 kỳ nghỉ lớn của Mỹ."""
    best = {}
    for y in years:
        hol = {"new_year": dt.date(y, 1, 1), "memorial": _nth_weekday(y, 5, 0, -1), "july4": dt.date(y, 7, 4),
               "labor": _nth_weekday(y, 9, 0, 1), "thanksgiving": _nth_weekday(y, 11, 3, 4), "christmas": dt.date(y, 12, 25)}
        for name, d0 in hol.items():
            for off in range(-window, window + 1):
                d = d0 + dt.timedelta(days=off)
                if d not in best or abs(off) < abs(best[d][1]): best[d] = (name, off)
    sch = T.StructType([T.StructField("fl_date", T.DateType()), T.StructField("holiday", T.StringType()), T.StructField("holiday_offset", T.IntegerType())])
    return spark.createDataFrame([(d, n, o) for d, (n, o) in best.items()], sch)

def peek(df, n=15):
    try:
        pdf = df.limit(n).toPandas()
        try: display(pdf)
        except NameError: print(pdf.to_string())
    except Exception:
        df.show(n, truncate=False)

def timed(fn):
    t = time.time(); r = fn(); return r, round(time.time() - t, 2)

### 3. Lõi KPI: cột cộng được → cuộn lên → tỷ lệ

In [3]:
# ── Ý TƯỞNG 1: chỉ tính các cột CỘNG ĐƯỢC (đếm, tổng) một lần cho mỗi tháng. Mọi mức ngày/tháng/năm là phép CỘNG lại;
#    tỷ lệ luôn tính từ tổng (không lấy trung bình của các tỷ lệ). Nhờ vậy các mức khớp nhau và thêm 1 tháng chỉ tốn 1 tháng. ──
def _add_exprs():
    a, dp = F.col("arr_delay_ok"), F.col("dep_delay_ok")
    cnt = lambda cond: F.sum(F.when(cond, 1).otherwise(0))
    E = [("flights", F.count(F.lit(1))), ("cancelled", F.sum("cancelled")), ("diverted", F.sum("diverted")),
         ("arr_n", F.count(a)), ("on_time", cnt(a < LATE_MIN)),
         ("delayed15", cnt(a >= 15)), ("delayed60", cnt(a >= 60)),
         ("sum_arr_delay", F.sum(a)), ("sum_arr_delay_pos", F.sum(F.when(a > 0, a).otherwise(0.0))),
         ("sum_arr_delay_late", F.sum(F.when(a >= LATE_MIN, a).otherwise(0.0))),
         ("dep_n", F.count(dp)), ("dep_delayed15", cnt(dp >= 15)), ("sum_dep_delay_pos", F.sum(F.when(dp > 0, dp).otherwise(0.0))),
         ("gain_n", F.count("air_gain")), ("sum_air_gain", F.sum("air_gain"))]
    E += [(f"cause_{k}", F.sum(f"d_{k}")) for k in CAUSES]
    E += [(f"cancel_{k}", cnt(F.col("cancel_code") == k.upper())) for k in "abcd"]       # A=hãng, B=thời tiết, C=NAS, D=an ninh
    return E

ADD_COLS = [n for n, _ in _add_exprs()]

def kpi_base(df, keys):
    return df.groupBy(*keys).agg(*[e.alias(n) for n, e in _add_exprs()])

def rollup(base, keys):
    """Cộng các cột cộng được theo khóa thô hơn. n_days = số ngày có dữ liệu (để tính chuyến/ngày, nhận biết năm chưa đủ)."""
    cols = set(base.columns)
    if "n_days" in cols: nd = [F.sum("n_days").alias("n_days")]
    elif {"year", "month", "day"} <= cols: nd = [F.countDistinct("year", "month", "day").alias("n_days")]
    else: nd = []
    return base.groupBy(*keys).agg(*nd, *[F.sum(c).alias(c) for c in ADD_COLS])

def _r(num, den):
    return F.when(F.col(den) > 0, F.col(num) / F.col(den))

def finalize(df):
    rates = {"cancel_rate": _r("cancelled", "flights"), "divert_rate": _r("diverted", "flights"),
             "otp_operated": _r("on_time", "arr_n"),       # đúng giờ trên các chuyến đã đo được giờ đến
             "otp_scheduled": _r("on_time", "flights"),    # đúng giờ trên TẤT CẢ chuyến lên lịch (hủy/chuyển hướng = không đúng giờ)
             "delay15_rate": _r("delayed15", "arr_n"), "severe60_rate": _r("delayed60", "arr_n"),
             "avg_arr_delay_net": _r("sum_arr_delay", "arr_n"),        # giữ số âm (đến sớm bù trừ)
             "avg_arr_delay_pos": _r("sum_arr_delay_pos", "arr_n"),    # chỉ tính phần trễ
             "avg_delay_when_late": _r("sum_arr_delay_late", "delayed15"),
             "dep_delay15_rate": _r("dep_delayed15", "dep_n"), "avg_dep_delay_pos": _r("sum_dep_delay_pos", "dep_n"),
             "avg_air_gain": _r("sum_air_gain", "gain_n"),
             **{f"cancel_share_{n}": _r(f"cancel_{k}", "cancelled") for k, n in zip("abcd", ("carrier", "weather", "nas", "security"))}}
    out = df.select("*", *[v.alias(k) for k, v in rates.items()])
    cc = [f"cause_{k}" for k in CAUSES]
    out = out.withColumn("cause_total", sum(F.coalesce(F.col(c), F.lit(0.0)) for c in cc))
    out = out.select("*", *[F.when(F.col("cause_total") > 0, F.col(c) / F.col("cause_total")).alias(c + "_share") for c in cc])
    z = lambda c: F.coalesce(F.col(c), F.lit(0.0))
    pen = W_DELAY * z("delay15_rate") + W_SEVERE * z("severe60_rate") + W_CANCEL * z("cancel_rate") + W_DIVERT * z("divert_rate")
    return out.withColumn("reliability_score", F.greatest(F.lit(0.0), F.least(F.lit(100.0), 100 * (1 - pen))))   # chỉ số tự định nghĩa 0-100

### 4. Box-plot từ biểu đồ tần suất

In [4]:
# ── Ý TƯỞNG 2: box-plot CHÍNH XÁC từ biểu đồ tần suất cộng được. ──
# Phân vị không cộng được, nhưng "số chuyến có delay = v phút" thì cộng được. BTS ghi delay là số phút nguyên nên biểu đồ tần suất
# (mỗi giá trị v một dòng) giữ nguyên thông tin: tính một lần mỗi tháng, mọi mức ngày/tháng/năm chỉ cần cộng lại rồi đọc phân vị.
def build_hist(df):
    one = lambda var, c: df.select("year", "month", "day", "carrier", F.lit(var).alias("var"), F.round(c).cast("int").alias("v"))
    return (one("arr", "arr_delay_ok").unionByName(one("dep", "dep_delay_ok")).where(F.col("v").isNotNull())
            .groupBy("year", "month", "day", "carrier", "var", "v").agg(F.count(F.lit(1)).alias("n")))

def box_from_hist(hist, keys, population):
    """Thống kê box-plot theo `keys`: population 'all' (mọi chuyến đã bay) hoặc 'late' (chỉ chuyến trễ ≥15 phút)."""
    g = keys + ["var"]
    h = hist if population == "all" else hist.where(F.col("v") >= LATE_MIN)
    d = h.groupBy(*g, "v").agg(F.sum("n").alias("n"))
    d = (d.withColumn("cum", F.sum("n").over(Window.partitionBy(*g).orderBy("v")))       # tần suất tích lũy
          .withColumn("total", F.sum("n").over(Window.partitionBy(*g))))
    q = lambda p: F.min(F.when(F.col("cum") >= F.greatest(F.lit(1), F.ceil(F.col("total") * p - 1e-9)), F.col("v")))   # phân vị theo hạng gần nhất
    st = (d.groupBy(*g).agg(F.max("total").alias("n"), F.min("v").alias("min"), F.max("v").alias("max"),
                            F.sum(F.col("v") * F.col("n")).alias("_s1"), F.sum(F.col("v") * F.col("v") * F.col("n")).alias("_s2"),
                            q(0.05).alias("p05"), q(0.25).alias("q1"), q(0.50).alias("median"), q(0.75).alias("q3"),
                            q(0.90).alias("p90"), q(0.95).alias("p95"), q(0.99).alias("p99"))
            .withColumn("mean", F.col("_s1") / F.col("n"))
            .withColumn("std", F.sqrt(F.greatest(F.lit(0.0), F.col("_s2") / F.col("n") - F.col("mean") ** 2))).drop("_s1", "_s2")
            .withColumn("iqr", F.col("q3") - F.col("q1"))
            .withColumn("fence_low", F.col("q1") - 1.5 * F.col("iqr")).withColumn("fence_high", F.col("q3") + 1.5 * F.col("iqr")))
    # Lượt 2: broadcast join hàng rào Tukey (bảng rất nhỏ) ngược vào biểu đồ → đầu râu thật + số ngoại lệ
    w = (d.join(F.broadcast(st.select(*g, "fence_low", "fence_high")), g).groupBy(*g).agg(
            F.min(F.when(F.col("v") >= F.col("fence_low"), F.col("v"))).alias("whisker_low"),
            F.max(F.when(F.col("v") <= F.col("fence_high"), F.col("v"))).alias("whisker_high"),
            F.sum(F.when(F.col("v") < F.col("fence_low"), F.col("n")).otherwise(0)).alias("n_out_low"),
            F.sum(F.when(F.col("v") > F.col("fence_high"), F.col("n")).otherwise(0)).alias("n_out_high")))
    return (st.join(w, g).withColumn("population", F.lit(population))
              .withColumn("out_high_rate", F.col("n_out_high") / F.col("n")).withColumn("reliable", F.col("n") >= MIN_BOX_N))

### 5. Pipeline: mỗi tháng một lần, rồi cuộn lên mọi mức

In [5]:
# ── Pipeline: mỗi tháng đọc dữ liệu thô MỘT lần → 5 bảng KPI cơ sở + 1 biểu đồ tần suất. Mọi thứ còn lại chỉ cộng bảng nhỏ. ──
GRAINS = {"day": ["year", "month", "day"],        # chuỗi ngày: xem 1 tháng (hướng A) hoặc cả năm (hướng B)
          "calendar_day": ["month", "day"],       # cùng ngày lịch qua các năm (25/12 của mọi năm)
          "month": ["year", "month"],             # các tháng trong 1 năm / chuỗi tháng
          "month_of_year": ["month"],             # cùng một tháng qua các năm → mùa vụ
          "year": ["year"]}
BASE_SPECS = {"day_carrier": ["year", "month", "day", "carrier"], "day_origin": ["year", "month", "day", "origin"],
              "month_carrier_origin": ["year", "month", "carrier", "origin"], "month_route": ["year", "month", "origin", "dest"],
              "prof_hour": ["year", "month", "dep_hour"]}

def write_part(df, sub):
    df.coalesce(1).write.mode("overwrite").partitionBy("year", "month").parquet(f"{ANALYTICS}/{sub}")

def month_built(y, m):
    path, fs = _hpath(f"{ANALYTICS}/base/hist/year={y}/month={m}")       # hist được ghi cuối cùng → có nghĩa là tháng đã xong
    return fs.exists(path)

def build_month(y, m):
    t0 = time.time()
    df = prepare(load_months([(y, m)], verbose=False)).persist(StorageLevel.MEMORY_AND_DISK)
    n = df.count()
    for name, keys in BASE_SPECS.items():
        write_part(kpi_base(df, keys), f"base/{name}")
    write_part(build_hist(df), "base/hist")
    df.unpersist()
    return n, round(time.time() - t0, 1)

def build_months(months):
    todo = [(y, m) for y, m in months if month_dir(y, m) and (FORCE_REBUILD or not month_built(y, m))]
    skip = [f"{y}-{m:02d}" for y, m in months if month_dir(y, m) and (y, m) not in todo]
    gone = [f"{y}-{m:02d}" for y, m in months if not month_dir(y, m)]
    if gone: print(f"⚠ Không có dữ liệu: {', '.join(gone)}")
    if skip: print(f"↷ Đã build trước đó (bỏ qua {len(skip)} tháng; đặt FORCE_REBUILD=True để tính lại)")
    for y, m in todo:
        n, sec = build_month(y, m)
        print(f"  {y}-{m:02d}: {n:>9,} dòng | {sec:>6}s", flush=True)

# Cuộn lên: (tên bảng, bảng cơ sở, khóa nhóm)
KPI_PLAN = [("day_overall", "day_carrier", GRAINS["day"]), ("calendar_day_overall", "day_carrier", GRAINS["calendar_day"]),
            ("month_overall", "day_carrier", GRAINS["month"]), ("month_of_year_overall", "day_carrier", GRAINS["month_of_year"]),
            ("year_overall", "day_carrier", GRAINS["year"]),
            ("month_carrier", "day_carrier", GRAINS["month"] + ["carrier"]), ("month_of_year_carrier", "day_carrier", GRAINS["month_of_year"] + ["carrier"]),
            ("year_carrier", "day_carrier", GRAINS["year"] + ["carrier"]),
            ("month_origin", "day_origin", GRAINS["month"] + ["origin"]), ("year_origin", "day_origin", GRAINS["year"] + ["origin"]),
            ("year_route", "month_route", GRAINS["year"] + ["origin", "dest"]),
            ("year_carrier_origin", "month_carrier_origin", GRAINS["year"] + ["carrier", "origin"]),
            ("hour_overall", "prof_hour", ["dep_hour"])]
BOX_PLAN = [("day", []), ("month", []), ("month", ["carrier"]), ("month_of_year", []), ("month_of_year", ["carrier"]), ("year", []), ("year", ["carrier"])]

def build_kpis():
    for name, base, keys in KPI_PLAN:
        b = spark.read.parquet(f"{ANALYTICS}/base/{base}")
        finalize(rollup(b, keys)).coalesce(1).write.mode("overwrite").parquet(f"{ANALYTICS}/kpi/{name}")

def build_boxes():
    hist = spark.read.parquet(f"{ANALYTICS}/base/hist")
    for grain, extra in BOX_PLAN:
        keys = GRAINS[grain] + extra
        out = box_from_hist(hist, keys, "all").unionByName(box_from_hist(hist, keys, "late"))
        out.coalesce(1).write.mode("overwrite").parquet(f"{ANALYTICS}/box/{grain}_{'carrier' if extra else 'overall'}")

def kpi(name):      return spark.read.parquet(f"{ANALYTICS}/kpi/{name}")
def box(name):      return spark.read.parquet(f"{ANALYTICS}/box/{name}")
def base_tbl(name): return spark.read.parquet(f"{ANALYTICS}/base/{name}")

### 6. Chạy pipeline

In [6]:
# ═══════════ CHẠY PIPELINE ═══════════
t0 = time.time()
print("Bước 1/3 – từng tháng (đọc dữ liệu thô một lần):");  build_months(MONTHS)
print("Bước 2/3 – cuộn lên các mức KPI…");                  build_kpis()
print("Bước 3/3 – box-plot từ biểu đồ tần suất…");           build_boxes()
print(f"Hoàn tất sau {round(time.time() - t0, 1)}s → {ANALYTICS}")

Bước 1/3 – từng tháng (đọc dữ liệu thô một lần):
↷ Đã build trước đó (bỏ qua 2 tháng; đặt FORCE_REBUILD=True để tính lại)

26/10/28 08:28:13 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.
26/10/28 08:28:29 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

  2022-03:   564,853 dòng |   33.4s

26/10/28 08:28:44 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2022-04:   556,502 dòng |   13.9s

26/10/28 08:28:58 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2022-05:   578,819 dòng |   12.8s

26/10/28 08:29:10 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2022-06:   577,283 dòng |   13.6s

26/10/28 08:29:24 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2022-07:   594,957 dòng |   11.5s

26/10/28 08:29:36 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2022-08:   589,810 dòng |   11.9s

26/10/28 08:29:47 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2022-09:   557,494 dòng |    9.7s

26/10/28 08:29:57 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2022-10:   572,287 dòng |    9.8s

26/10/28 08:30:07 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2022-11:   546,410 dòng |    9.3s

26/10/28 08:30:16 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2022-12:   557,095 dòng |    9.3s

26/10/28 08:30:25 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-01:   538,837 dòng |    9.3s

26/10/28 08:30:35 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-02:   502,749 dòng |    7.9s

26/10/28 08:30:43 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-03:   580,322 dòng |    9.3s

26/10/28 08:30:52 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-04:   561,441 dòng |    8.3s

26/10/28 08:31:00 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-05:   579,958 dòng |    8.8s

26/10/28 08:31:09 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-06:   577,262 dòng |    8.8s

26/10/28 08:31:18 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-07:   601,866 dòng |    8.9s

26/10/28 08:31:27 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-08:   602,987 dòng |    8.7s

26/10/28 08:31:35 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-09:   569,338 dòng |    9.2s

26/10/28 08:31:45 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-10:   598,968 dòng |    9.5s

26/10/28 08:31:54 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-11:   563,777 dòng |    8.1s

26/10/28 08:32:02 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2023-12:   570,394 dòng |    7.9s

26/10/28 08:32:10 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-01:   547,271 dòng |    9.9s

26/10/28 08:32:20 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-02:   519,221 dòng |    8.4s

26/10/28 08:32:28 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-03:   591,767 dòng |    9.2s

26/10/28 08:32:38 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-04:   582,185 dòng |    9.2s

26/10/28 08:32:47 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-05:   609,743 dòng |    9.2s

26/10/28 08:32:56 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-06:   611,132 dòng |    8.4s

26/10/28 08:33:04 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-07:   634,613 dòng |   10.4s

26/10/28 08:33:15 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-08:   619,025 dòng |    8.9s

26/10/28 08:33:23 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-09:   582,622 dòng |    7.9s

26/10/28 08:33:31 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-10:   615,497 dòng |    9.1s

26/10/28 08:33:40 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-11:   575,404 dòng |    8.5s

26/10/28 08:33:49 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2024-12:   590,581 dòng |   10.2s

26/10/28 08:33:59 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-01:   539,747 dòng |    9.4s

26/10/28 08:34:09 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-02:   504,884 dòng |    7.6s

26/10/28 08:34:16 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-03:   600,872 dòng |    8.3s

26/10/28 08:34:25 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-04:   583,950 dòng |    8.4s

26/10/28 08:34:33 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-05:   605,648 dòng |    8.7s

26/10/28 08:34:42 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-06:   611,575 dòng |    9.1s

26/10/28 08:34:51 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-07:   631,428 dòng |    9.5s

26/10/28 08:35:00 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-08:   602,378 dòng |    9.6s

26/10/28 08:35:10 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-09:   562,439 dòng |    8.4s

26/10/28 08:35:18 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-10:   605,844 dòng |    8.0s

26/10/28 08:35:26 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-11:   570,550 dòng |    8.4s

26/10/28 08:35:35 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2025-12:   582,304 dòng |   10.3s

26/10/28 08:35:45 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2026-01:   544,003 dòng |   11.9s

26/10/28 08:35:57 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2026-02:   515,037 dòng |    8.9s

26/10/28 08:36:06 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

  2026-03:   612,102 dòng |   12.9s

Bước 2/3 – cuộn lên các mức KPI…

Bước 3/3 – box-plot từ biểu đồ tần suất…

Hoàn tất sau 592.9s → /aero/analytics/eda

### 7. Các hàm phân tích

In [7]:
# ═══════════ CÁC PHÂN TÍCH (đọc từ bảng KPI nhỏ đã tính; mỗi hàm trả về một DataFrame nhỏ) ═══════════

# ── Tổng quan và MỨC NĂM ──
def overview():
    return (kpi("year_overall").withColumn("flights_per_day", F.col("flights") / F.col("n_days")).orderBy("year")
            .select("year", "n_days", "flights", "flights_per_day", "cancel_rate", "divert_rate", "otp_operated", "otp_scheduled",
                    "avg_arr_delay_net", "avg_arr_delay_pos", "avg_delay_when_late", "delay15_rate", "severe60_rate",
                    "avg_air_gain", "reliability_score"))

# ── MỨC THÁNG ──
def monthly_trend(metric="otp_scheduled"):
    """Chuỗi tháng + trung bình trượt 3 tháng (window) + so cùng kỳ năm trước (self-join t-12)."""
    cur = kpi("month_overall").withColumn("t", F.col("year") * 12 + F.col("month")).select("year", "month", "t", "flights", metric)
    prev = cur.select((F.col("t") + 12).alias("t"), F.col(metric).alias(f"{metric}_prev_year"))
    return (cur.join(prev, "t", "left").withColumn(f"{metric}_ma3", F.avg(metric).over(Window.orderBy("t").rangeBetween(-2, 0)))
               .withColumn("yoy_change", F.col(metric) - F.col(f"{metric}_prev_year")).orderBy("t").drop("t"))

def seasonality(metric="delay15_rate"):
    """Chỉ số mùa vụ = giá trị của tháng-trong-năm / giá trị chung (>1: tháng xấu hơn bình thường nếu là chỉ số 'xấu')."""
    g = finalize(rollup(kpi("year_overall"), [])).select(F.col(metric).alias("overall_value"))
    return (kpi("month_of_year_overall").select("month", "flights", metric).crossJoin(g)
            .withColumn("seasonality_index", F.col(metric) / F.col("overall_value")).orderBy("month"))

def month_matrix(metric="otp_scheduled"):
    """PIVOT: hàng = tháng, cột = năm → so cùng tháng qua các năm."""
    k = kpi("month_overall"); years = sorted(r[0] for r in k.select("year").distinct().collect())
    return k.groupBy("month").pivot("year", years).agg(F.first(metric)).orderBy("month")

# ── MỨC NGÀY ──
def day_in_month(y, m):
    """Hướng A: các ngày của MỘT tháng, kèm xếp hạng ngày xấu nhất."""
    k = kpi("day_overall").where((F.col("year") == y) & (F.col("month") == m))
    return (k.withColumn("dow", ((F.dayofweek(F.make_date("year", "month", "day")) + 5) % 7) + 1)      # 1=Thứ hai … 7=Chủ nhật
             .withColumn("rank_worst", F.dense_rank().over(Window.orderBy(F.desc("delay15_rate")))).orderBy("day")
             .select("day", "dow", "flights", "otp_scheduled", "cancel_rate", "delay15_rate", "avg_arr_delay_pos", "rank_worst"))

def daily_anomalies(metric="delay15_rate", window_days=28, top=10):
    """Hướng B: z-score từng ngày so với nền 28 ngày trước (window theo khoảng ngày); gắn ngày lễ (broadcast join)."""
    d = kpi("day_overall").withColumn("d", F.make_date("year", "month", "day")).withColumn("dn", F.datediff("d", F.lit("1970-01-01").cast("date")))
    w = Window.orderBy("dn").rangeBetween(-window_days, -1)
    hol = holiday_df().select(F.col("fl_date").alias("d"), "holiday", "holiday_offset")
    z = (d.withColumn("z", (F.col(metric) - F.avg(metric).over(w)) / F.stddev(metric).over(w))
          .join(F.broadcast(hol), "d", "left").withColumn("holiday", F.coalesce("holiday", F.lit("none"))))
    return z.orderBy(F.desc(F.abs("z"))).limit(top).select("d", "flights", metric, "z", "cancel_rate", "avg_arr_delay_pos", "holiday", "holiday_offset")

def calendar_day_across_years(top=10):
    """Hướng B: cùng một ngày lịch gộp qua các năm."""
    return kpi("calendar_day_overall").orderBy(F.desc("delay15_rate")).limit(top).select("month", "day", "n_days", "flights", "delay15_rate", "cancel_rate", "otp_scheduled")

def _with_calendar():
    d = kpi("day_overall").withColumn("fl_date", F.make_date("year", "month", "day"))
    return d.withColumn("dow", ((F.dayofweek("fl_date") + 5) % 7) + 1)

def dow_profile():
    return finalize(rollup(_with_calendar(), ["dow"])).orderBy("dow").select("dow", "flights", "otp_scheduled", "delay15_rate", "cancel_rate", "avg_arr_delay_pos")

def holiday_effect():
    """Mức nâng (lift) so với ngày thường theo số ngày cách lễ (broadcast join bảng ngày lễ)."""
    d = _with_calendar().join(F.broadcast(holiday_df()), "fl_date", "left")
    d = d.withColumn("holiday", F.coalesce("holiday", F.lit("none"))).withColumn("holiday_offset", F.coalesce("holiday_offset", F.lit(0)))
    h = finalize(rollup(d, ["holiday", "holiday_offset"]))
    b = h.where(F.col("holiday") == "none").select(F.col("delay15_rate").alias("b_delay"), F.col("cancel_rate").alias("b_cancel"))
    return (h.where(F.col("holiday") != "none").crossJoin(b).withColumn("delay15_lift", F.col("delay15_rate") / F.col("b_delay"))
             .withColumn("cancel_lift", F.col("cancel_rate") / F.col("b_cancel")).orderBy("holiday", "holiday_offset")
             .select("holiday", "holiday_offset", "flights", "delay15_rate", "delay15_lift", "cancel_rate", "cancel_lift"))

def hour_profile():
    """Trễ tích lũy theo giờ khởi hành: chuyến sáng sớm ít trễ, chiều tối trễ nhiều (hiệu ứng máy bay đến trễ)."""
    return kpi("hour_overall").orderBy("dep_hour").select("dep_hour", "flights", "otp_scheduled", "delay15_rate", "avg_dep_delay_pos",
                                                         "cause_late_aircraft_share", "cancel_rate")

# ── HÃNG BAY ──
def carrier_ranking(year=None):
    k = kpi("year_carrier").where(F.col("flights") >= MIN_FLIGHTS).join(F.broadcast(carrier_lookup()), "carrier", "left")
    if year: k = k.where(F.col("year") == year)
    return (k.withColumn("rank", F.dense_rank().over(Window.partitionBy("year").orderBy(F.desc("reliability_score")))).orderBy("year", "rank")
             .select("year", "rank", "carrier", "carrier_name", "flights", "otp_scheduled", "cancel_rate", "delay15_rate",
                     "avg_delay_when_late", "severe60_rate", "reliability_score"))

def carrier_yoy():
    """Hãng nào cải thiện / xấu đi so với năm trước (self-join theo year-1)."""
    k = kpi("year_carrier").where(F.col("flights") >= MIN_FLIGHTS)
    p = k.select((F.col("year") + 1).alias("year"), "carrier", F.col("otp_scheduled").alias("otp_prev"), F.col("cancel_rate").alias("cancel_prev"))
    return (k.join(p, ["year", "carrier"]).withColumn("otp_change", F.col("otp_scheduled") - F.col("otp_prev"))
             .withColumn("cancel_change", F.col("cancel_rate") - F.col("cancel_prev")).orderBy("year", F.desc("otp_change"))
             .select("year", "carrier", "flights", "otp_prev", "otp_scheduled", "otp_change", "cancel_prev", "cancel_rate", "cancel_change"))

def carrier_matrix(metric="otp_scheduled", by="year"):
    """PIVOT: hàng = hãng, cột = năm (hoặc tháng-trong-năm)."""
    k = kpi(f"{by}_carrier"); col = "month" if by == "month_of_year" else "year"
    vals = sorted(r[0] for r in k.select(col).distinct().collect())
    return k.where(F.col("flights") >= MIN_FLIGHTS).groupBy("carrier").pivot(col, vals).agg(F.first(metric)).orderBy("carrier")

def unpivot_causes(df, keys):
    """UNPIVOT: từ 5 cột nguyên nhân (dạng rộng) sang dạng dài (cause, minutes, share)."""
    stack = "stack(5, 'carrier', cause_carrier, 'weather', cause_weather, 'nas', cause_nas, 'security', cause_security, 'late_aircraft', cause_late_aircraft) as (cause, minutes)"
    return (df.select(*keys, "cause_total", F.expr(stack))
              .withColumn("share", F.when(F.col("cause_total") > 0, F.col("minutes") / F.col("cause_total"))))

# ── SÂN BAY, MẠNG LƯỚI, TUYẾN ──
def worst_airports(year=None, top=10):
    k = kpi("year_origin").where(F.col("flights") >= MIN_FLIGHTS)
    if year: k = k.where(F.col("year") == year)
    return k.orderBy(F.desc("avg_dep_delay_pos")).limit(top).select("year", "origin", "flights", "otp_scheduled", "cancel_rate", "avg_dep_delay_pos", "cause_late_aircraft_share")

def concentration():
    """HHI thị phần hãng tại sân bay đi (>0.25 = tập trung cao, theo ngưỡng DOJ 2.500/10.000)."""
    co = kpi("year_carrier_origin").select("year", "origin", "carrier", "flights")
    tot = co.groupBy("year", "origin").agg(F.sum("flights").alias("airport_flights"))
    j = co.join(tot, ["year", "origin"]).withColumn("share", F.col("flights") / F.col("airport_flights"))
    top = (j.withColumn("rk", F.row_number().over(Window.partitionBy("year", "origin").orderBy(F.desc("share")))).where("rk = 1")
             .select("year", "origin", F.col("carrier").alias("dominant_carrier"), F.col("share").alias("dominant_share")))
    hhi = j.groupBy("year", "origin", "airport_flights").agg(F.sum(F.col("share") ** 2).alias("hhi"))
    return (hhi.join(top, ["year", "origin"]).where(F.col("airport_flights") >= MIN_FLIGHTS)
               .withColumn("hhi_class", F.when(F.col("hhi") > 0.25, "concentrated").when(F.col("hhi") > 0.15, "moderate").otherwise("competitive")))

def _pagerank(pdf, d=0.85, iters=60):
    import numpy as np, pandas as pd
    nodes = sorted(set(pdf["origin"]) | set(pdf["dest"])); idx = {n: i for i, n in enumerate(nodes)}; n = len(nodes)
    src, dst, w = pdf["origin"].map(idx).values, pdf["dest"].map(idx).values, pdf["flights"].values.astype(float)
    out = np.zeros(n); np.add.at(out, src, w); pr = np.full(n, 1.0 / n)
    for _ in range(iters):
        c = np.zeros(n); np.add.at(c, dst, pr[src] * w / out[src]); pr = (1 - d) / n + d * (c + pr[out == 0].sum() / n)
    return pd.DataFrame({"airport": nodes, "pagerank": pr})

def airport_network(year=None, top=15):
    """Đồ thị sân bay (cạnh = tuyến có hướng, trọng số = số chuyến): bậc vào/ra, lưu lượng, mất cân bằng, PageRank (đồ thị nhỏ → tính ở driver)."""
    e = kpi("year_route")
    if year: e = e.where(F.col("year") == year)
    e = e.groupBy("origin", "dest").agg(F.sum("flights").alias("flights"))
    o = e.groupBy(F.col("origin").alias("airport")).agg(F.count("dest").alias("out_degree"), F.sum("flights").alias("flights_out"))
    i = e.groupBy(F.col("dest").alias("airport")).agg(F.count("origin").alias("in_degree"), F.sum("flights").alias("flights_in"))
    nodes = o.join(i, "airport", "outer").na.fill(0).withColumn("flow_balance", F.col("flights_out") - F.col("flights_in"))
    pr = spark.createDataFrame(_pagerank(e.select("origin", "dest", "flights").toPandas()))
    return nodes.join(pr, "airport", "left").orderBy(F.desc("pagerank")).limit(top)

def route_excess_delay(year=None, hint="merge", top=10):
    """Tuyến nào trễ NHIỀU HƠN mức nền của sân bay đi? Ghép hai bảng lớn bằng sort-merge join (hint='merge') hoặc broadcast."""
    r = kpi("year_route").where(F.col("flights") >= MIN_FLIGHTS).select("year", "origin", "dest", "flights", F.col("avg_arr_delay_net").alias("route_delay"))
    o = kpi("year_origin").select("year", "origin", F.col("avg_arr_delay_net").alias("origin_baseline"))
    if year: r, o = r.where(F.col("year") == year), o.where(F.col("year") == year)
    return (r.hint(hint).join(o.hint(hint), ["year", "origin"]).withColumn("excess_delay", F.col("route_delay") - F.col("origin_baseline"))
             .orderBy(F.desc("excess_delay")))

def enrich_routes(year=None):
    """NHIỀU JOIN liên tiếp (tuyến ⨝ nhóm sân bay đi ⨝ nhóm sân bay đến ⨝ mức nền sân bay đi), có kiểm tra số dòng không bị nhân bản."""
    r = kpi("year_route")
    if year: r = r.where(F.col("year") == year)
    n0 = r.count()
    o = kpi("year_origin").groupBy("origin").agg(F.sum("flights").alias("f"))
    tier = o.withColumn("airport_tier", F.when(F.row_number().over(Window.orderBy(F.desc("f"))) <= 30, "large").otherwise("other")).select("origin", "airport_tier")
    base = kpi("year_origin").select("year", "origin", F.col("avg_arr_delay_net").alias("origin_baseline"))
    j = (r.join(F.broadcast(tier.withColumnRenamed("airport_tier", "origin_tier")), "origin")
          .join(F.broadcast(tier.withColumnRenamed("origin", "dest").withColumnRenamed("airport_tier", "dest_tier")), "dest")
          .join(base, ["year", "origin"], "left"))
    n1 = j.count()
    print(f"enrich_routes: {n0} dòng trước join, {n1} sau join → {'OK, không nhân bản' if n0 == n1 else 'CẢNH BÁO: số dòng thay đổi!'}")
    return j.select("year", "origin", "dest", F.concat_ws("→", "origin_tier", "dest_tier").alias("tier_pair"), "flights", "otp_scheduled", "avg_arr_delay_net", "origin_baseline")

# ── BOX-PLOT ──
def box_summary(grain="year", dim="overall", var="arr", population="late", where=None):
    b = box(f"{grain}_{dim}").where((F.col("var") == var) & (F.col("population") == population) & F.col("reliable"))
    if where is not None: b = b.where(where)
    keys = [c for c in b.columns if c in ("year", "month", "day", "carrier")]
    return b.select(*keys, "n", "min", "q1", "median", "q3", "whisker_high", "p90", "p95", "p99", "max", "mean", "n_out_high", "out_high_rate").orderBy(*keys)

### 8. Xem kết quả

In [8]:
# ═══════════ XEM KẾT QUẢ ═══════════
def section(t): print("\n" + "═" * 8 + " " + t + " " + "═" * 8)
y0, m0 = MONTHS[0]

section("Tổng quan theo năm (n_days = số ngày có dữ liệu; năm cuối có thể chưa đủ)"); peek(overview())
section("MỨC NĂM – xếp hạng hãng theo reliability_score và thay đổi so với năm trước"); peek(carrier_ranking(), 40); peek(carrier_yoy(), 40)
section("MỨC THÁNG – chuỗi tháng + trung bình trượt + so cùng kỳ"); peek(monthly_trend(), 60)
section("MỨC THÁNG – mùa vụ (tháng-trong-năm so với toàn kỳ) và ma trận tháng × năm"); peek(seasonality(), 12); peek(month_matrix(), 12)
section(f"MỨC NGÀY – hướng A: các ngày của tháng {y0}-{m0:02d}"); peek(day_in_month(y0, m0), 31)
section("MỨC NGÀY – hướng B: ngày bất thường và ngày lịch xấu nhất qua các năm"); peek(daily_anomalies()); peek(calendar_day_across_years())
section("HỒ SƠ – theo giờ khởi hành / thứ trong tuần / ngày lễ"); peek(hour_profile(), 24); peek(dow_profile(), 7); peek(holiday_effect(), 50)
section("NGUYÊN NHÂN TRỄ – dạng dài (unpivot) theo năm"); peek(unpivot_causes(kpi("year_overall"), ["year"]), 20)
section("HÃNG – ma trận hãng × năm (pivot)"); peek(carrier_matrix("otp_scheduled", "year"), 40)
section("SÂN BAY – sân bay trễ nhiều nhất và mức tập trung hãng (HHI)"); peek(worst_airports()); peek(concentration().orderBy(F.desc("hhi")), 10)
section("MẠNG LƯỚI – bậc vào/ra, lưu lượng, PageRank"); peek(airport_network())
section("TUYẾN – trễ vượt mức nền sân bay đi (sort-merge join) và bảng tuyến nhiều join"); peek(route_excess_delay()); peek(enrich_routes(), 10)
section("BOX-PLOT – delay đến toàn bộ chuyến đã bay, theo năm"); peek(box_summary("year", "overall", "arr", "all"), 10)
section("BOX-PLOT – delay đến của chuyến TRỄ, theo hãng và năm"); peek(box_summary("year", "carrier", "arr", "late"), 40)

════════ Tổng quan theo năm (n_days = số ngày có dữ liệu; năm cuối có thể chưa đủ) ════════

,year,n_days,flights,flights_per_day,cancel_rate,divert_rate,otp_operated,otp_scheduled,avg_arr_delay_net,avg_arr_delay_pos,avg_delay_when_late,delay15_rate,severe60_rate,avg_air_gain,reliability_score
0,2022,365,6729125,18435.958904,0.026941,0.002352,0.789223,0.766105,7.035647,15.233843,67.283050,0.210777,0.070074,5.493606,87.374401
1,2023,365,6847899,18761.367123,0.012842,0.002417,0.794362,0.782241,6.627152,15.231402,69.011667,0.205638,0.068507,5.573830,88.014827
2,2024,366,7079061,19341.696721,0.013606,0.002472,0.791828,0.779098,7.098219,15.896336,71.584450,0.208172,0.073455,5.490939,87.769822
3,2025,365,7001619,19182.517808,0.014693,0.002751,0.776925,0.763373,8.504504,17.266110,72.941107,0.223075,0.081773,4.957091,86.829735
4,2026,90,1671142,18568.244444,0.032915,0.002550,0.782392,0.754644,7.262870,17.248902,74.892455,0.217608,0.079642,6.642932,86.691116

════════ MỨC NĂM – xếp hạng hãng theo reliability_score và thay đổi so với năm trước ════════

,year,rank,carrier,carrier_name,flights,otp_scheduled,cancel_rate,delay15_rate,avg_delay_when_late,severe60_rate,reliability_score
0,2022,1,DL,Delta,893172,0.825301,0.016029,0.159664,69.284329,0.051274,90.581278
1,2022,2,QX,Horizon,88791,0.817921,0.017029,0.166401,52.558943,0.043847,90.368405
2,2022,3,OO,SkyWest,733576,0.816097,0.018173,0.166488,81.366734,0.062379,89.960079
3,2022,4,MQ,Envoy,248059,0.806453,0.022374,0.173147,60.844262,0.053704,89.697748
4,2022,5,9E,Endeavor,231941,0.805265,0.035362,0.163375,79.397582,0.062406,89.688454
5,2022,6,UA,United,626473,0.790092,0.018973,0.192529,71.179057,0.069238,88.501731
6,2022,7,AS,Alaska,228384,0.772769,0.027226,0.203182,51.271160,0.049934,88.146781
7,2022,8,OH,PSA,214450,0.779608,0.030832,0.193339,72.763894,0.072620,88.096338
8,2022,9,YX,Republic,316524,0.764245,0.046954,0.195941,68.281701,0.071640,87.583500
9,2022,10,YV,Mesa,114779,0.774271,0.033194,0.196946,90.857903,0.086631,87.576998
10,2022,11,HA,Hawaiian,73865,0.757747,0.009206,0.234344,45.554433,0.038590,87.275244
11,2022,12,AA,American,874145,0.749378,0.029622,0.225634,75.919239,0.081253,86.339459
12,2022,13,WN,Southwest,1307149,0.731829,0.032632,0.241908,51.457726,0.062287,85.833008
13,2022,14,NK,Spirit,232400,0.729570,0.030004,0.246543,66.855317,0.086805,85.178150
14,2022,15,F9,Frontier,155482,0.660945,0.028653,0.318290,72.177279,0.119844,80.963277
15,2022,16,B6,JetBlue,273058,0.646343,0.037424,0.326023,77.248041,0.138905,79.967255
16,2022,17,G4,Allegiant,116877,0.633940,0.035165,0.341196,68.276835,0.118934,79.669497
17,2023,1,YX,Republic,295275,0.843465,0.027645,0.130668,65.496461,0.043897,91.886983
18,2023,2,9E,Endeavor,201520,0.841118,0.021050,0.139169,75.920447,0.052934,91.447380
19,2023,3,DL,Delta,984986,0.826077,0.010169,0.163688,71.435303,0.055633,90.438381
20,2023,4,OO,SkyWest,675163,0.824632,0.012222,0.162590,77.765994,0.058854,90.372656
21,2023,5,OH,PSA,194144,0.820638,0.013243,0.166168,74.406614,0.058585,90.175937
22,2023,6,MQ,Envoy,227488,0.808403,0.010071,0.181548,58.625156,0.052836,89.603058
23,2023,7,AS,Alaska,245344,0.794782,0.008058,0.196371,49.909041,0.044056,89.084123
24,2023,8,UA,United,732212,0.780711,0.014026,0.206083,71.033763,0.074594,87.840304
25,2023,9,WN,Southwest,1438465,0.772542,0.009959,0.218094,49.689708,0.053038,87.775501
26,2023,10,HA,Hawaiian,80967,0.751961,0.013005,0.237444,47.771178,0.043098,86.936271
27,2023,11,AA,American,940531,0.759367,0.010609,0.230427,85.552523,0.086654,86.467062
28,2023,12,G4,Allegiant,115539,0.733709,0.006768,0.259148,80.343979,0.094158,84.975875
29,2023,13,NK,Spirit,263871,0.695074,0.017001,0.291410,71.595150,0.112275,82.748616
30,2023,14,F9,Frontier,177542,0.669892,0.021257,0.314339,77.988281,0.125292,81.237067
31,2023,15,B6,JetBlue,274852,0.670779,0.020968,0.311853,84.650904,0.139738,81.067053
32,2024,1,YX,Republic,301465,0.841730,0.018496,0.140715,67.482336,0.049650,91.499165
33,2024,2,HA,Hawaiian,78530,0.835795,0.010467,0.154548,46.191032,0.026368,91.478804
34,2024,3,9E,Endeavor,200094,0.820564,0.023029,0.158311,79.924098,0.064115,90.216091
35,2024,4,DL,Delta,1009174,0.818056,0.009064,0.172640,71.953014,0.059075,89.948974
36,2024,5,OO,SkyWest,744658,0.798302,0.011451,0.189980,80.371055,0.073491,88.729811
37,2024,6,WN,Southwest,1419419,0.785662,0.008294,0.206048,53.955469,0.056981,88.339903
38,2024,7,UA,United,760451,0.785989,0.016409,0.198590,72.711644,0.075349,88.139124
39,2024,8,MQ,Envoy,279955,0.778286,0.014234,0.208603,64.619237,0.069360,87.815117

,year,carrier,flights,otp_prev,otp_scheduled,otp_change,cancel_prev,cancel_rate,cancel_change
0,2023,G4,115539,0.633940,0.733709,0.099769,0.035165,0.006768,-0.028397
1,2023,YX,295275,0.764245,0.843465,0.079219,0.046954,0.027645,-0.019308
2,2023,OH,194144,0.779608,0.820638,0.041030,0.030832,0.013243,-0.017590
3,2023,WN,1438465,0.731829,0.772542,0.040713,0.032632,0.009959,-0.022674
4,2023,9E,201520,0.805265,0.841118,0.035852,0.035362,0.021050,-0.014312
5,2023,B6,274852,0.646343,0.670779,0.024437,0.037424,0.020968,-0.016457
6,2023,AS,245344,0.772769,0.794782,0.022013,0.027226,0.008058,-0.019168
7,2023,AA,940531,0.749378,0.759367,0.009989,0.029622,0.010609,-0.019013
8,2023,F9,177542,0.660945,0.669892,0.008948,0.028653,0.021257,-0.007396
9,2023,OO,675163,0.816097,0.824632,0.008535,0.018173,0.012222,-0.005950
10,2023,MQ,227488,0.806453,0.808403,0.001950,0.022374,0.010071,-0.012303
11,2023,DL,984986,0.825301,0.826077,0.000775,0.016029,0.010169,-0.005861
12,2023,HA,80967,0.757747,0.751961,-0.005787,0.009206,0.013005,0.003799
13,2023,UA,732212,0.790092,0.780711,-0.009380,0.018973,0.014026,-0.004947
14,2023,NK,263871,0.729570,0.695074,-0.034495,0.030004,0.017001,-0.013004
15,2024,HA,78530,0.751961,0.835795,0.083835,0.013005,0.010467,-0.002538
16,2024,B6,240282,0.670779,0.730650,0.059871,0.020968,0.015544,-0.005423
17,2024,NK,261103,0.695074,0.744802,0.049727,0.017001,0.019142,0.002141
18,2024,G4,117210,0.733709,0.767725,0.034016,0.006768,0.017217,0.010449
19,2024,F9,208624,0.669892,0.695035,0.025143,0.021257,0.023176,0.001919
20,2024,WN,1419419,0.772542,0.785662,0.013119,0.009959,0.008294,-0.001665
21,2024,UA,760451,0.780711,0.785989,0.005278,0.014026,0.016409,0.002383
22,2024,YX,301465,0.843465,0.841730,-0.001735,0.027645,0.018496,-0.009149
23,2024,DL,1009174,0.826077,0.818056,-0.008021,0.010169,0.009064,-0.001105
24,2024,9E,200094,0.841118,0.820564,-0.020553,0.021050,0.023029,0.001979
25,2024,OO,744658,0.824632,0.798302,-0.026330,0.012222,0.011451,-0.000771
26,2024,MQ,279955,0.808403,0.778286,-0.030117,0.010071,0.014234,0.004164
27,2024,AS,245819,0.794782,0.761857,-0.032925,0.008058,0.019571,0.011513
28,2024,AA,984306,0.759367,0.725009,-0.034357,0.010609,0.015495,0.004886
29,2024,OH,227971,0.820638,0.767549,-0.053089,0.013243,0.016454,0.003211
30,2025,NK,194515,0.744802,0.772485,0.027684,0.019142,0.015048,-0.004094
31,2025,F9,198065,0.695035,0.706788,0.011753,0.023176,0.017711,-0.005464
32,2025,AA,973653,0.725009,0.727006,0.001997,0.015495,0.018157,0.002662
33,2025,AS,245588,0.761857,0.757529,-0.004328,0.019571,0.012110,-0.007462
34,2025,B6,231413,0.730650,0.723447,-0.007203,0.015544,0.016529,0.000985
35,2025,WN,1391885,0.785662,0.777551,-0.008110,0.008294,0.008477,0.000183
36,2025,MQ,299322,0.778286,0.769857,-0.008429,0.014234,0.022427,0.008193
37,2025,UA,795271,0.785989,0.776543,-0.009446,0.016409,0.008207,-0.008201
38,2025,HA,80084,0.835795,0.819452,-0.016343,0.010467,0.008241,-0.002226
39,2025,OO,839821,0.798302,0.778983,-0.019319,0.011451,0.014102,0.002651

════════ MỨC THÁNG – chuỗi tháng + trung bình trượt + so cùng kỳ ════════

26/10/28 08:39:35 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:35 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:35 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:35 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:35 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:35 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:35 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

,year,month,flights,otp_scheduled,otp_scheduled_prev_year,otp_scheduled_ma3,yoy_change
0,2022,1,537902,0.755671,NaN,0.755671,NaN
1,2022,2,495713,0.767646,NaN,0.761658,NaN
2,2022,3,564853,0.769924,NaN,0.764414,NaN
3,2022,4,556502,0.756790,NaN,0.764787,NaN
4,2022,5,578819,0.771324,NaN,0.766013,NaN
5,2022,6,577283,0.733011,NaN,0.753708,NaN
6,2022,7,594957,0.746992,NaN,0.750442,NaN
7,2022,8,589810,0.754648,NaN,0.744884,NaN
8,2022,9,557494,0.819476,NaN,0.773705,NaN
9,2022,10,572287,0.832511,NaN,0.802212,NaN
10,2022,11,546410,0.799621,NaN,0.817203,NaN
11,2022,12,557095,0.687150,NaN,0.773094,NaN
12,2023,1,538837,0.761796,0.755671,0.749523,0.006125
13,2023,2,502749,0.795184,0.767646,0.748044,0.027538
14,2023,3,580322,0.750426,0.769924,0.769136,-0.019498
15,2023,4,561441,0.755853,0.756790,0.767155,-0.000936
16,2023,5,579958,0.812662,0.771324,0.772981,0.041338
17,2023,6,577262,0.711178,0.733011,0.759898,-0.021833
18,2023,7,601866,0.694470,0.746992,0.739437,-0.052522
19,2023,8,602987,0.769010,0.754648,0.724886,0.014362
20,2023,9,569338,0.801260,0.819476,0.754914,-0.018216
21,2023,10,598968,0.839808,0.832511,0.803359,0.007297
22,2023,11,563777,0.862158,0.799621,0.834409,0.062537
23,2023,12,570394,0.837646,0.687150,0.846537,0.150495
24,2024,1,547271,0.728999,0.761796,0.809601,-0.032797
25,2024,2,519221,0.834390,0.795184,0.800345,0.039206
26,2024,3,591767,0.783046,0.750426,0.782145,0.032620
27,2024,4,582185,0.802094,0.755853,0.806510,0.046241
28,2024,5,609743,0.723174,0.812662,0.769438,-0.089489
29,2024,6,611132,0.738510,0.711178,0.754592,0.027332
30,2024,7,634613,0.680845,0.694470,0.714176,-0.013625
31,2024,8,619025,0.747128,0.769010,0.722161,-0.021882
32,2024,9,582622,0.838595,0.801260,0.755523,0.037335
33,2024,10,615497,0.858121,0.839808,0.814615,0.018313
34,2024,11,575404,0.848157,0.862158,0.848291,-0.014001
35,2024,12,590581,0.780775,0.837646,0.829018,-0.056870
36,2025,1,539747,0.785811,0.728999,0.804914,0.056812
37,2025,2,504884,0.779137,0.834390,0.781908,-0.055253
38,2025,3,600872,0.792626,0.783046,0.785858,0.009580
39,2025,4,583950,0.794804,0.802094,0.788856,-0.007289
40,2025,5,605648,0.753798,0.723174,0.780409,0.030624
41,2025,6,611575,0.703212,0.738510,0.750605,-0.035298
42,2025,7,631428,0.690180,0.680845,0.715730,0.009335
43,2025,8,602378,0.763330,0.747128,0.718907,0.016202
44,2025,9,562439,0.827590,0.838595,0.760367,-0.011005
45,2025,10,605844,0.791159,0.858121,0.794026,-0.066962
46,2025,11,570550,0.773159,0.848157,0.797303,-0.074998
47,2025,12,582304,0.719231,0.780775,0.761183,-0.061544
48,2026,1,544003,0.753207,0.785811,0.748532,-0.032604
49,2026,2,515037,0.782750,0.779137,0.751729,0.003612
50,2026,3,612102,0.732272,0.792626,0.756076,-0.060355

════════ MỨC THÁNG – mùa vụ (tháng-trong-năm so với toàn kỳ) và ma trận tháng × năm ════════

    month  flights  delay15_rate  overall_value  seasonality_index
0       1  2707760      0.210272       0.212267           0.990603
1       2  2537604      0.189502       0.212267           0.892754
2       3  2949916      0.220273       0.212267           1.037716
3       4  2284078      0.209343       0.212267           0.986225
4       5  2374168      0.223648       0.212267           1.053618
5       6  2377252      0.261154       0.212267           1.230307
6       7  2462864      0.277351       0.212267           1.306616
7       8  2414200      0.225354       0.212267           1.061654
8       9  2271893      0.168408       0.212267           0.793379
9      10  2392596      0.162539       0.212267           0.765728
10     11  2256141      0.169010       0.212267           0.796214
11     12  2300374      0.226062       0.212267           1.064990

    month      2022      2023      2024      2025      2026
0       1  0.755671  0.761796  0.728999  0.785811  0.753207
1       2  0.767646  0.795184  0.834390  0.779137  0.782750
2       3  0.769924  0.750426  0.783046  0.792626  0.732272
3       4  0.756790  0.755853  0.802094  0.794804       NaN
4       5  0.771324  0.812662  0.723174  0.753798       NaN
5       6  0.733011  0.711178  0.738510  0.703212       NaN
6       7  0.746992  0.694470  0.680845  0.690180       NaN
7       8  0.754648  0.769010  0.747128  0.763330       NaN
8       9  0.819476  0.801260  0.838595  0.827590       NaN
9      10  0.832511  0.839808  0.858121  0.791159       NaN
10     11  0.799621  0.862158  0.848157  0.773159       NaN
11     12  0.687150  0.837646  0.780775  0.719231       NaN

════════ MỨC NGÀY – hướng A: các ngày của tháng 2022-01 ════════

26/10/28 08:39:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

,day,dow,flights,otp_scheduled,cancel_rate,delay15_rate,avg_arr_delay_pos,rank_worst
0,1,6,15852,0.530974,0.144020,0.376565,31.335531,3
1,2,7,19058,0.440235,0.127086,0.494791,38.049497,1
2,3,1,19216,0.483711,0.154038,0.425738,32.108242,2
3,4,2,16965,0.603890,0.079340,0.342848,25.204939,4
4,5,3,16863,0.625452,0.093459,0.308801,20.615833,5
5,6,4,18235,0.660269,0.110173,0.256331,19.847869,8
6,7,5,18241,0.614550,0.125651,0.296340,21.753625,6
7,8,6,15303,0.713128,0.070182,0.229526,15.902782,10
8,9,7,18157,0.735915,0.060252,0.215707,14.732699,11
9,10,1,17897,0.832821,0.041236,0.130498,9.106580,22
10,11,2,16308,0.875521,0.034094,0.092884,5.738691,27
11,12,3,16794,0.909194,0.023997,0.067371,4.699853,31
12,13,4,18128,0.882006,0.023003,0.096565,6.425302,26
13,14,5,18535,0.829026,0.023253,0.149640,9.737576,18
14,15,6,14781,0.823625,0.023476,0.155111,10.480464,17
15,16,7,16967,0.632817,0.164555,0.240020,18.104049,9
16,17,1,18149,0.757177,0.067166,0.187489,14.137527,13
17,18,2,16334,0.913065,0.011510,0.076075,5.720852,30
18,19,3,16815,0.865061,0.019209,0.115422,8.523048,24
19,20,4,18512,0.799373,0.033330,0.170423,11.942594,14
20,21,5,18504,0.814256,0.031020,0.156713,10.599541,16
21,22,6,14927,0.834997,0.026998,0.140117,10.257123,20
22,23,7,18074,0.782284,0.017262,0.200916,13.496044,12
23,24,1,18054,0.815996,0.020328,0.165515,12.410559,15
24,25,2,16307,0.892071,0.015944,0.092004,6.602085,28
25,26,3,16789,0.913098,0.007981,0.078781,5.837510,29
26,27,4,18547,0.854100,0.012024,0.133472,9.420327,21
27,28,5,18506,0.681076,0.069275,0.262061,19.804625,7
28,29,6,14946,0.712967,0.195705,0.112296,8.807981,25
29,30,7,18087,0.790789,0.076961,0.142660,11.338788,19
30,31,1,18051,0.867376,0.016453,0.117816,9.167737,23

════════ MỨC NGÀY – hướng B: ngày bất thường và ngày lịch xấu nhất qua các năm ════════

26/10/28 08:39:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

,d,flights,delay15_rate,z,cancel_rate,avg_arr_delay_pos,holiday,holiday_offset
0,2022-12-23,19145,0.621411,5.054402,0.275842,67.173268,christmas,-2.0
1,2024-07-19,21468,0.582746,4.883301,0.165269,69.690261,none,NaN
2,2022-12-22,19182,0.494896,4.715650,0.129913,44.770100,christmas,-3.0
3,2022-11-04,19012,0.334866,4.615949,0.040396,28.532650,none,NaN
4,2024-01-09,16775,0.451746,4.434085,0.075648,46.410863,none,NaN
5,2024-12-20,20561,0.352188,4.338113,0.019600,28.877708,none,NaN
6,2025-11-09,20442,0.451418,4.132050,0.121319,45.072663,none,NaN
7,2025-02-13,19715,0.423962,4.090451,0.024702,34.946124,none,NaN
8,2023-11-26,20578,0.288918,3.883421,0.001166,19.395008,thanksgiving,3.0
9,2026-03-16,20678,0.554295,3.729939,0.195715,64.267411,none,NaN

   month  day  n_days  flights  delay15_rate  cancel_rate  otp_scheduled
0     12   26       4    78034      0.333501     0.077325       0.612682
1      7   14       4    83023      0.333350     0.041230       0.634764
2     12   27       4    76885      0.331149     0.054289       0.630669
3     12   28       4    76813      0.322853     0.050734       0.640959
4      7   16       4    77751      0.321126     0.035562       0.651336
5      7   19       4    78977      0.319817     0.052167       0.643580
6      7   21       4    83086      0.318858     0.036408       0.653949
7      6   26       4    81327      0.315389     0.046577       0.648616
8      3   16       5    95841      0.313549     0.058347       0.643305
9      6   27       4    81225      0.312235     0.050822       0.650034

════════ HỒ SƠ – theo giờ khởi hành / thứ trong tuần / ngày lễ ════════

,dep_hour,flights,otp_scheduled,delay15_rate,avg_dep_delay_pos,cause_late_aircraft_share,cancel_rate
0,0,48651,0.787301,0.196648,17.619657,0.381914,0.018109
1,1,15798,0.764844,0.217118,19.311562,0.428582,0.021142
2,2,6369,0.751295,0.231078,17.903516,0.510789,0.021981
3,3,3934,0.759786,0.223233,18.738701,0.506003,0.021352
4,4,1911,0.772894,0.199458,16.664139,0.405125,0.034014
5,5,812483,0.892810,0.089392,9.004396,0.148886,0.017895
6,6,2059073,0.880887,0.101277,8.635685,0.138122,0.017817
7,7,2039349,0.857814,0.126463,9.222324,0.161902,0.015811
8,8,2004155,0.843197,0.142394,9.736867,0.232172,0.014525
9,9,1654747,0.830242,0.156206,10.755872,0.311156,0.013818
10,10,1836843,0.818776,0.167354,12.011378,0.370303,0.014238
11,11,1820154,0.803644,0.183155,13.177852,0.392110,0.013462
12,12,1751926,0.787416,0.198314,14.595817,0.403003,0.014704
13,13,1760393,0.767673,0.218501,15.958794,0.413781,0.014345
14,14,1677639,0.744096,0.240639,17.753184,0.408100,0.016769
15,15,1689729,0.726624,0.258060,18.934826,0.408439,0.017390
16,16,1681417,0.709600,0.274312,20.178292,0.432277,0.019244
17,17,1825084,0.698750,0.284279,21.461256,0.438114,0.021146
18,18,1774003,0.688605,0.293969,22.627345,0.465434,0.022472
19,19,1593062,0.679776,0.302036,23.809628,0.488989,0.023860
20,20,1316406,0.678160,0.303650,23.951139,0.489263,0.024090
21,21,997215,0.694069,0.287359,23.224649,0.454745,0.024173
22,22,713394,0.703535,0.276904,22.890270,0.433144,0.025328
23,23,245111,0.766057,0.217939,18.690157,0.379240,0.018669

   dow  flights  otp_scheduled  delay15_rate  cancel_rate  avg_arr_delay_pos
0    1  4386534       0.768166      0.215199     0.018746          16.430953
1    2  4033892       0.807834      0.178427     0.014428          13.328144
2    3  4064039       0.797050      0.188242     0.015666          13.897476
3    4  4342385       0.762979      0.221048     0.017910          16.340225
4    5  4375447       0.750171      0.233521     0.018732          17.525661
5    6  3799469       0.775805      0.207996     0.017944          15.887468
6    7  4327080       0.744726      0.237132     0.021126          18.222767

,holiday,holiday_offset,flights,delay15_rate,delay15_lift,cancel_rate,cancel_lift
0,christmas,-3,79429,0.265303,1.259192,0.033993,1.966636
1,christmas,-2,78151,0.278211,1.320459,0.071720,4.149353
2,christmas,-1,61913,0.270505,1.283882,0.062023,3.588300
3,christmas,0,62587,0.177995,0.844806,0.056098,3.245533
4,christmas,1,78034,0.333501,1.582876,0.077325,4.473637
5,christmas,2,76885,0.331149,1.571717,0.054289,3.140872
6,christmas,3,76813,0.322853,1.532340,0.050734,2.935182
7,july4,-3,77112,0.279825,1.328119,0.026961,1.559811
8,july4,-2,75440,0.245593,1.165647,0.016331,0.944818
9,july4,-1,77181,0.203346,0.965130,0.006763,0.391291
10,july4,0,69132,0.136415,0.647458,0.007782,0.450238
11,july4,1,75444,0.223916,1.062761,0.012380,0.716245
12,july4,2,78767,0.257759,1.223387,0.010004,0.578790
13,july4,3,81803,0.276397,1.311850,0.017212,0.995801
14,labor,-3,80807,0.233387,1.107712,0.009888,0.572054
15,labor,-2,65350,0.157453,0.747312,0.010176,0.588729
16,labor,-1,69727,0.152385,0.723259,0.007228,0.418185
17,labor,0,80120,0.155001,0.735672,0.003457,0.200022
18,labor,1,72117,0.125584,0.596053,0.001761,0.101884
19,labor,2,70425,0.122896,0.583293,0.003323,0.192233
20,labor,3,77773,0.173525,0.823592,0.010659,0.616687
21,memorial,-3,81066,0.250357,1.188257,0.021526,1.245363
22,memorial,-2,67788,0.194252,0.921968,0.010843,0.627298
23,memorial,-1,73489,0.193958,0.920575,0.009090,0.525888
24,memorial,0,80675,0.225109,1.068422,0.015457,0.894266
25,memorial,1,75206,0.206236,0.978848,0.017312,1.001608
26,memorial,2,75909,0.214999,1.020439,0.017679,1.022819
27,memorial,3,80663,0.227089,1.077822,0.032369,1.872716
28,new_year,-3,77942,0.307014,1.457164,0.044546,2.577196
29,new_year,-2,77113,0.224451,1.065298,0.005797,0.335366
30,new_year,-1,64721,0.195247,0.926690,0.006304,0.364716
31,new_year,0,83188,0.230965,1.096217,0.033454,1.935494
32,new_year,1,95742,0.289831,1.375611,0.037006,2.140957
33,new_year,2,93890,0.309408,1.468529,0.047747,2.762414
34,new_year,3,90582,0.282712,1.341820,0.031033,1.795388
35,thanksgiving,-3,79882,0.168297,0.798779,0.003993,0.231037
36,thanksgiving,-2,80709,0.170162,0.807633,0.002280,0.131897
37,thanksgiving,-1,81504,0.165965,0.787710,0.001460,0.084471
38,thanksgiving,0,45755,0.090085,0.427565,0.000743,0.042991
39,thanksgiving,1,69829,0.130259,0.618243,0.001504,0.086995
40,thanksgiving,2,78252,0.220987,1.048857,0.022606,1.307892
41,thanksgiving,3,83632,0.311197,1.477017,0.012172,0.704230

════════ NGUYÊN NHÂN TRỄ – dạng dài (unpivot) theo năm ════════

    year  cause_total          cause     minutes     share
0   2022   92635169.0        carrier  36853634.0  0.397836
1   2022   92635169.0        weather   5143449.0  0.055524
2   2022   92635169.0            nas  15566212.0  0.168038
3   2022   92635169.0       security    196222.0  0.002118
4   2022   92635169.0  late_aircraft  34875652.0  0.376484
5   2023   95698124.0        carrier  34862074.0  0.364292
6   2023   95698124.0        weather   5009341.0  0.052345
7   2023   95698124.0            nas  17310028.0  0.180882
8   2023   95698124.0       security    206677.0  0.002160
9   2023   95698124.0  late_aircraft  38310004.0  0.400321
10  2025  111934625.0        carrier  36326377.0  0.324532
11  2025  111934625.0        weather   7108714.0  0.063508
12  2025  111934625.0            nas  24483761.0  0.218733
13  2025  111934625.0       security    152802.0  0.001365
14  2025  111934625.0  late_aircraft  43862971.0  0.391862
15  2024  103794712.0        carrier  35823263.0  0.345136
16  2024  103794712.0        weather   6195873.0  0.059694
17  2024  103794712.0            nas  19621964.0  0.189046
18  2024  103794712.0       security    179928.0  0.001733
19  2024  103794712.0  late_aircraft  41973684.0  0.404391

════════ HÃNG – ma trận hãng × năm (pivot) ════════

   carrier      2022      2023      2024      2025      2026
0       9E  0.805265  0.841118  0.820564       NaN       NaN
1       AA  0.749378  0.759367  0.725009  0.727006  0.728921
2       AS  0.772769  0.794782  0.761857  0.757529  0.782329
3       B6  0.646343  0.670779  0.730650  0.723447  0.649965
4       DL  0.825301  0.826077  0.818056  0.791191  0.782669
5       F9  0.660945  0.669892  0.695035  0.706788  0.710940
6       G4  0.633940  0.733709  0.767725  0.744574  0.736295
7       HA  0.757747  0.751961  0.835795  0.819452       NaN
8       MQ  0.806453  0.808403  0.778286  0.769857  0.784224
9       NK  0.729570  0.695074  0.744802  0.772485  0.589351
10      OH  0.779608  0.820638  0.767549  0.689585  0.671482
11      OO  0.816097  0.824632  0.798302  0.778983  0.752386
12      QX  0.817921       NaN       NaN       NaN       NaN
13      UA  0.790092  0.780711  0.785989  0.776543  0.799628
14      WN  0.731829  0.772542  0.785662  0.777551  0.783929
15      YV  0.774271       NaN       NaN       NaN       NaN
16      YX  0.764245  0.843465  0.841730  0.757684  0.717476

════════ SÂN BAY – sân bay trễ nhiều nhất và mức tập trung hãng (HHI) ════════

,year,origin,flights,otp_scheduled,cancel_rate,avg_dep_delay_pos,cause_late_aircraft_share
0,2025,CKB,205,0.468293,0.024390,68.560000,0.449257
1,2026,MQT,314,0.541401,0.114650,60.194245,0.172515
2,2026,MGM,322,0.645963,0.099379,51.420690,0.534527
3,2025,HGR,316,0.490506,0.018987,47.238710,0.522490
4,2024,HTS,426,0.544601,0.032864,45.766990,0.401568
5,2025,MGW,727,0.742779,0.042641,45.143678,0.444533
6,2025,USA,710,0.542254,0.008451,45.045455,0.469716
7,2026,CHO,391,0.611253,0.076726,42.540166,0.337559
8,2026,LAN,492,0.650407,0.032520,41.962185,0.209723
9,2024,CKB,207,0.628019,0.024155,40.292079,0.343561

,year,origin,airport_flights,hhi,dominant_carrier,dominant_share,hhi_class
0,2022,ADQ,949,1.0,AS,1.0,concentrated
1,2022,ASE,6465,1.0,OO,1.0,concentrated
2,2022,ABI,1908,1.0,MQ,1.0,concentrated
3,2022,ABY,963,1.0,9E,1.0,concentrated
4,2022,ABR,713,1.0,OO,1.0,concentrated
5,2022,ALW,614,1.0,QX,1.0,concentrated
6,2022,ACV,1968,1.0,OO,1.0,concentrated
7,2022,ALO,697,1.0,MQ,1.0,concentrated
8,2022,APN,628,1.0,OO,1.0,concentrated
9,2022,ACY,3285,1.0,NK,1.0,concentrated

════════ MẠNG LƯỚI – bậc vào/ra, lưu lượng, PageRank ════════

,airport,out_degree,flights_out,in_degree,flights_in,flow_balance,pagerank
0,DEN,202,1261402,201,1261324,78,0.045288
1,DFW,198,1263644,197,1263594,50,0.044703
2,ORD,198,1208560,197,1208477,83,0.041279
3,ATL,164,1385020,165,1384904,116,0.041072
4,CLT,154,842554,154,842576,-22,0.026350
5,SEA,102,702137,101,702096,41,0.023371
6,PHX,123,783714,123,783682,32,0.022313
7,LAX,124,814624,122,814657,-33,0.021593
8,LAS,140,781185,138,781200,-15,0.021189
9,MCO,110,673350,110,673358,-8,0.018256
10,MSP,130,507165,129,507172,-7,0.018159
11,LGA,97,664365,98,664373,-8,0.018151
12,DTW,116,535700,116,535672,28,0.016672
13,DCA,107,599887,107,599955,-68,0.016308
14,SFO,88,578727,88,578875,-148,0.016260

════════ TUYẾN – trễ vượt mức nền sân bay đi (sort-merge join) và bảng tuyến nhiều join ════════

    year origin dest  flights  route_delay  origin_baseline  excess_delay
0   2023    SNA  PVU      325    64.536977         5.054874     59.482103
1   2026    AUS  PHL      219    65.980769         7.494682     58.486087
2   2025    SNA  PVU      387    61.481675         5.620430     55.861245
3   2025    LEX  SFB      224    62.931818         8.433297     54.498521
4   2023    ONT  JFK      365    56.264045         4.654823     51.609222
5   2026    ORD  HSV      228    63.465116        17.061150     46.403966
6   2025    DFW  ALB      302    59.392491        14.935696     44.456796
7   2022    RNO  JFK      285    48.098901         4.990407     43.108494
8   2026    CVG  DCA      258    50.106838         8.709483     41.397355
9   2024    JAC  DFW      622    56.271382        15.864545     40.406836
10  2024    ABQ  JFK      259    44.326772         4.291413     40.035358
11  2025    MRY  DFW      332    45.363354         6.292022     39.071332
12  2023    IAH  JFK      406    48.658228         9.673699     38.984529
13  2023    BUR  JFK      364    40.426426         2.955831     37.470595
14  2024    STS  DFW      210    48.699029        11.393559     37.305470

enrich_routes: 33373 dòng trước join, 33372 sau join → CẢNH BÁO: số dòng thay đổi!

26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/10/28 08:39:51 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

,year,origin,dest,tier_pair,flights,otp_scheduled,avg_arr_delay_net,origin_baseline
0,2024,MCO,DTW,large→large,3798,0.748815,11.663276,10.650136
1,2024,DCA,BOS,large→large,9658,0.787637,5.819648,5.559043
2,2024,DFW,GRR,large→other,1125,0.649778,23.806685,13.908512
3,2024,MSP,DTW,large→large,2327,0.846584,1.405440,4.043018
4,2024,PHL,CHS,large→other,1374,0.781659,7.582046,8.535498
5,2024,ATL,SAT,large→other,2986,0.793034,5.058804,6.824339
6,2024,PVD,CLT,other→large,1584,0.780303,12.308184,4.876391
7,2024,MDW,DTW,large→large,2083,0.786846,6.559051,6.238456
8,2024,GRR,CLT,other→large,1067,0.773196,11.632227,5.561234
9,2024,RSW,BOS,other→large,2219,0.707075,15.632719,9.255328

════════ BOX-PLOT – delay đến toàn bộ chuyến đã bay, theo năm ════════

,year,n,min,q1,median,q3,whisker_high,p90,p95,p99,max,mean,n_out_high,out_high_rate
0,2022,6532012,-100,-14,-5,10,46,42,79,199,3423,7.035647,592130,0.090650
1,2023,6743403,-119,-15,-6,9,45,41,78,205,4405,6.627152,607450,0.090081
2,2024,6965247,-126,-15,-6,9,45,43,83,215,3803,7.098219,665279,0.095514
3,2025,6879484,-128,-15,-6,11,50,48,91,225,4336,8.504504,659913,0.095925
4,2026,1611874,-90,-17,-7,10,50,47,90,233,3339,7.262870,150340,0.093270

════════ BOX-PLOT – delay đến của chuyến TRỄ, theo hãng và năm ════════

,year,carrier,n,min,q1,median,q3,whisker_high,p90,p95,p99,max,mean,n_out_high,out_high_rate
0,2022,9E,36473,15,25,44,89,185,161,235,724,1368,79.397582,2798,0.076714
1,2022,AA,190872,15,24,42,82,169,147,214,672,3423,75.919239,14686,0.076942
2,2022,AS,45003,15,21,33,59,116,108,151,263,908,51.271160,3920,0.087105
3,2022,B6,85373,15,27,50,95,197,164,222,382,2029,77.248041,5694,0.066696
4,2022,DL,140056,15,23,38,74,150,141,211,568,1285,69.284329,12578,0.089807
5,2022,F9,47981,15,26,45,83,168,146,201,448,1378,72.177279,3574,0.074488
6,2022,G4,38373,15,25,42,78,157,141,194,376,1919,68.276835,3106,0.080942
7,2022,HA,17131,15,20,28,45,82,82,123,303,1805,45.554433,1686,0.098418
8,2022,MQ,41891,15,23,37,72,145,127,173,326,1550,60.844262,3116,0.074384
9,2022,NK,55480,15,24,42,79,161,139,192,358,1598,66.855317,4074,0.073432
10,2022,OH,40071,15,24,43,86,179,155,214,404,1612,72.763894,2955,0.073744
11,2022,OO,119580,15,24,43,87,181,165,250,751,2363,81.366734,10234,0.085583
12,2022,QX,14497,15,21,34,62,123,111,154,265,976,52.558943,1198,0.082638
13,2022,UA,118018,15,24,42,81,166,147,209,457,1637,71.179057,9340,0.079140
14,2022,WN,305255,15,23,35,61,118,105,146,248,731,51.457726,24232,0.079383
15,2022,YV,21795,15,27,50,102,214,183,261,852,2076,90.857903,1565,0.071805
16,2022,YX,58949,15,25,43,82,167,142,191,345,1395,68.281701,4084,0.069280
17,2023,9E,27403,15,25,44,86,177,152,219,651,1409,75.920447,2071,0.075576
18,2023,AA,213850,15,25,43,86,177,164,260,826,4405,85.552523,19063,0.089142
19,2023,AS,47648,15,21,32,55,106,101,144,279,1294,49.909041,4338,0.091043
20,2023,B6,83550,15,28,52,101,210,179,244,479,2511,84.650904,5883,0.070413
21,2023,DL,159257,15,24,40,78,159,146,216,562,1331,71.435303,13667,0.085817
22,2023,F9,54525,15,27,47,89,182,155,217,586,1416,77.988281,3906,0.071637
23,2023,G4,29653,15,25,43,83,170,155,226,905,2067,80.343979,2522,0.085050
24,2023,HA,18958,15,21,30,49,91,83,122,328,1623,47.771178,1609,0.084872
25,2023,MQ,40793,15,22,36,67,134,118,165,336,1625,58.625156,3140,0.076974
26,2023,NK,75428,15,26,45,86,176,155,211,372,1434,71.595150,5717,0.075794
27,2023,OH,31750,15,23,40,83,173,159,228,544,2016,74.406614,2691,0.084756
28,2023,OO,108100,15,24,41,83,171,156,234,713,3045,77.765994,9268,0.085735
29,2023,UA,148386,15,24,42,83,171,150,211,417,1631,71.033763,11546,0.077811
30,2023,WN,309963,15,22,34,58,112,102,141,238,812,49.689708,25479,0.082200
31,2023,YX,37435,15,23,39,77,158,138,191,350,1389,65.496461,2871,0.076693
32,2024,9E,30882,15,26,47,91,188,163,229,672,1305,79.924098,2321,0.075157
33,2024,AA,252485,15,26,46,91,188,171,257,738,3803,85.717219,21303,0.084373
34,2024,AS,53044,15,22,33,58,112,102,145,264,917,50.528655,4482,0.084496
35,2024,B6,60121,15,27,49,94,194,166,228,434,2512,78.700005,4337,0.072138
36,2024,DL,172265,15,24,40,79,161,153,226,507,1278,71.953014,15838,0.091940
37,2024,F9,58481,15,27,47,89,182,157,223,659,1432,79.401601,4390,0.075067
38,2024,G4,24897,15,26,46,93,193,176,264,963,1575,88.731614,2123,0.085271
39,2024,HA,11998,15,20,28,46,85,81,115,331,1734,46.191032,1096,0.091349

### 9. Kỹ thuật đặc biệt và bằng chứng Spark (chạy trên 1 tháng)

In [9]:
# ═══════════ KỸ THUẬT ĐẶC BIỆT (chạy trên 1 tháng nhỏ): UDF, custom aggregation, lan truyền trễ, bằng chứng Spark ═══════════
df_demo = prepare(load_months(MONTHS[:1], verbose=False)).cache()

# ── UDF có lý do nghiệp vụ: phân tầng mức độ nghiêm trọng, đối chiếu với biểu thức Spark tham chiếu ──
def severity_expr():
    a = F.col("arr_delay")
    return (F.when(F.col("cancelled") == 1, "1_cancelled").when(F.col("diverted") == 1, "2_diverted").when(a.isNull(), "0_unknown")
             .when(a < 0, "3_early").when(a < 15, "4_ontime").when(a < 30, "5_minor").when(a < 60, "6_moderate")
             .when(a < 180, "7_major").otherwise("8_severe"))
def _severity_py(a, cancelled, diverted):
    if cancelled == 1: return "1_cancelled"
    if diverted == 1: return "2_diverted"
    if a is None: return "0_unknown"
    return "3_early" if a < 0 else "4_ontime" if a < 15 else "5_minor" if a < 30 else "6_moderate" if a < 60 else "7_major" if a < 180 else "8_severe"
severity_udf = F.udf(_severity_py, T.StringType())
t = df_demo.select(severity_expr().alias("ref"), severity_udf("arr_delay", "cancelled", "diverted").alias("udf"))
section("UDF vs biểu thức tham chiếu → số dòng KHÔNG khớp / tổng"); print(t.where(F.col("ref") != F.col("udf")).count(), "/", t.count())

# ── Custom aggregation: trung bình cắt 1% hai đầu (pandas grouped-aggregate UDF). Không trộn được với hàm gộp thường → ghép bằng join ──
section("Custom aggregation: trimmed mean vs mean vs median")
try:
    import pandas as pd
    @F.pandas_udf("double")
    def trimmed_mean(v: pd.Series) -> float:
        v = v.dropna()
        if len(v) == 0: return float("nan")
        lo, hi = v.quantile(0.01), v.quantile(0.99)
        return float(v[(v >= lo) & (v <= hi)].mean())
    plain = df_demo.groupBy("year", "carrier").agg(F.count("arr_delay_ok").alias("n"), F.avg("arr_delay_ok").alias("mean"),
                                                   F.expr("percentile_approx(arr_delay_ok, 0.5, 10000)").alias("median"))
    tm = df_demo.groupBy("year", "carrier").agg(trimmed_mean("arr_delay_ok").alias("trimmed_mean"))
    peek(plain.join(tm, ["year", "carrier"]).orderBy("year", "carrier"), 20)
except Exception as e:
    print("⚠ Không chạy được pandas UDF ở đây:", type(e).__name__, "(cần pandas + pyarrow, Java 8/11/17)")

# ── Lan truyền trễ theo máy bay (cần TAIL_NUM): chuyến trước đến trễ → chuyến sau đi trễ? Chỉ xét chuyến liền kề (đến X rồi đi từ X) ──
def delay_propagation(df, min_n=100):
    if df.where(F.col("tail").isNotNull()).limit(1).count() == 0:
        print("ℹ Không có TAIL_NUM → bỏ qua"); return None
    ts = F.to_timestamp(F.concat_ws(" ", F.col("fl_date").cast("string"), F.format_string("%02d:%02d", "dep_hour", "dep_min")))
    w = Window.partitionBy("tail").orderBy("sched_ts")
    d = (df.where(F.col("tail").isNotNull() & (F.col("cancelled") == 0)).withColumn("sched_ts", ts)
           .withColumn("prev_arr_delay", F.lag("arr_delay_ok").over(w)).withColumn("prev_dest", F.lag("dest").over(w))
           .where((F.col("prev_dest") == F.col("origin")) & F.col("prev_arr_delay").isNotNull() & F.col("dep_delay_ok").isNotNull())
           .withColumn("prev_state", F.when(F.col("prev_arr_delay") < 0, "1_prev_early").when(F.col("prev_arr_delay") < 15, "2_prev_ontime")
                                      .when(F.col("prev_arr_delay") < 45, "3_prev_late15_44").otherwise("4_prev_late45plus")))
    return (d.groupBy("prev_state").agg(F.count(F.lit(1)).alias("n"), F.avg("dep_delay_ok").alias("avg_dep_delay"),
                                         F.avg((F.col("dep_delay_ok") >= 15).cast("double")).alias("dep_late15_rate"))
             .where(F.col("n") >= min_n).orderBy("prev_state"))
section("Lan truyền trễ theo máy bay"); peek(delay_propagation(df_demo))

# ── Bằng chứng kỹ thuật: partition pruning, broadcast vs sort-merge join, cache, bucketing, tối ưu truy vấn ──
EVIDENCE = {}
def plan_text(df, mode="formatted"):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf): df.explain(mode=mode)
    return buf.getvalue()

@contextlib.contextmanager
def conf(settings):
    old = {k: spark.conf.get(k, None) for k in settings}
    for k, v in settings.items(): spark.conf.set(k, v)
    try: yield
    finally:
        for k, v in old.items(): spark.conf.unset(k) if v is None else spark.conf.set(k, v)

def save_evidence(name, text):
    os.makedirs(EVIDENCE_DIR, exist_ok=True)
    open(os.path.join(EVIDENCE_DIR, name + ".txt"), "w", encoding="utf-8").write(text)

def evidence_pruning():
    """Lọc theo year/month → số phân vùng quét giảm; plan có PartitionFilters."""
    full = spark.read.parquet(PROCESSED).select("year")
    one = spark.read.parquet(PROCESSED).where((F.col("year") == y0) & (F.col("month") == m0)).select("year")
    plan = plan_text(one.select(F.count(F.lit(1))))
    res = {"scan_partitions_no_filter": full.rdd.getNumPartitions(), "scan_partitions_with_filter": one.rdd.getNumPartitions(),
           "partition_filters": re.findall(r"PartitionFilters: \[.*?\]", plan)}
    save_evidence("pruning", json.dumps(res, indent=2) + "\n\n" + plan); return res

def evidence_joins():
    """Broadcast join vs sort-merge join cho cùng một phép ghép (kết quả phải giống nhau)."""
    out = {}
    with conf({"spark.sql.adaptive.enabled": "false"}):          # tắt AQE để plan hiển thị đúng chiến lược đã chọn
        for hint in ("broadcast", "merge"):
            df = route_excess_delay(hint=hint); plan = plan_text(df); cnt, sec = timed(lambda: df.count())
            out[hint] = {"rows": cnt, "seconds": sec, "strategy": "BroadcastHashJoin" if "BroadcastHashJoin" in plan else "SortMergeJoin" if "SortMergeJoin" in plan else "other"}
            save_evidence(f"join_{hint}", plan)
    out["same_rowcount"] = out["broadcast"]["rows"] == out["merge"]["rows"]; return out

def evidence_cache(df):
    def run(d):
        d.groupBy("carrier").agg(F.avg("arr_delay_ok")).collect(); d.groupBy("origin").agg(F.sum("operated")).collect()
        d.groupBy("dep_hour").agg(F.count(F.lit(1))).collect()
    raw = prepare(load_months(MONTHS[:1], verbose=False))
    _, t_no = timed(lambda: [run(raw) for _ in range(3)])
    c = raw.cache(); _, t_fill = timed(lambda: c.count()); _, t_c = timed(lambda: [run(c) for _ in range(3)]); c.unpersist()
    return {"no_cache_s": t_no, "cache_fill_s": t_fill, "cached_3_runs_s": t_c, "speedup_x": round(t_no / t_c, 2) if t_c else None}

def evidence_bucketing(df, buckets=8, table="aero_bts_bucketed"):
    """Bucketing theo hãng: gom nhóm theo cột bucket không cần shuffle (Exchange). Cần catalog (saveAsTable) → chỉ sống trong session."""
    cols = ["carrier", "origin", "arr_delay_ok", "operated"]
    spark.sql(f"DROP TABLE IF EXISTS {table}")
    df.select(*cols).write.mode("overwrite").bucketBy(buckets, "carrier").sortBy("carrier").saveAsTable(table)
    q = lambda d: d.groupBy("carrier").agg(F.avg("arr_delay_ok").alias("avg_delay"), F.sum("operated").alias("operated"))
    plain, buck = q(df.select(*cols)), q(spark.table(table))
    with conf({"spark.sql.adaptive.enabled": "false"}): p1, p2 = plan_text(plain), plan_text(buck)
    _, t1 = timed(lambda: plain.collect()); _, t2 = timed(lambda: buck.collect())
    save_evidence("bucketing_plain", p1); save_evidence("bucketing_bucketed", p2); spark.sql(f"DROP TABLE IF EXISTS {table}")
    return {"exchange_plain": p1.count("Exchange"), "exchange_bucketed": p2.count("Exchange"), "plain_s": t1, "bucketed_s": t2}

def evidence_optimization():
    """Bộ lọc bằng biểu thức Spark (đẩy xuống Parquet: PushedFilters) vs bằng Python UDF (không đẩy xuống được)."""
    raw = load_months(MONTHS[:1], verbose=False); a = COLMAP.get("arr_delay") or "ARR_DELAY"
    is_late = F.udf(lambda x: x is not None and x >= 15, T.BooleanType()); res = {}
    for name, d in (("native_filter", raw.where(F.col(a) >= 15).select(F.count(F.lit(1)))), ("udf_filter", raw.where(is_late(F.col(a))).select(F.count(F.lit(1))))):
        plan = plan_text(d); rows, sec = timed(lambda: d.collect()[0][0]); save_evidence(f"optimization_{name}", plan)
        res[name] = {"late_flights": rows, "seconds": sec, "pushed_filters": re.findall(r"PushedFilters: \[.*?\]", plan)}
    res["same_result"] = res["native_filter"]["late_flights"] == res["udf_filter"]["late_flights"]; return res

section("BẰNG CHỨNG KỸ THUẬT SPARK")
for fn, args in ((evidence_pruning, ()), (evidence_joins, ()), (evidence_cache, (df_demo,)), (evidence_bucketing, (df_demo,)), (evidence_optimization, ())):
    try:
        EVIDENCE[fn.__name__] = fn(*args); print(fn.__name__, "→", json.dumps(EVIDENCE[fn.__name__], ensure_ascii=False, default=str))
    except Exception as e:
        print(fn.__name__, "✗", type(e).__name__, str(e)[:300])
save_evidence("summary", json.dumps(EVIDENCE, indent=2, ensure_ascii=False, default=str))
print("\nPlan chi tiết đã lưu trong:", os.path.abspath(EVIDENCE_DIR))

26/10/28 08:43:45 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

════════ UDF vs biểu thức tham chiếu → số dòng KHÔNG khớp / tổng ════════

0 / 537902

════════ Custom aggregation: trimmed mean vs mean vs median ════════

    year carrier      n       mean  median  trimmed_mean
0   2022      9E  20259   1.984254   -10.0     -1.704643
1   2022      AA  66370  -1.075832   -11.0     -4.810863
2   2022      AS  15204   5.233294    -4.0      3.330340
3   2022      B6  19192  18.721082    -2.0     15.010150
4   2022      DL  66573  -0.228486    -9.0     -3.111283
5   2022      F9  11486  10.955163    -4.0      7.998491
6   2022      G4   7975  12.243135    -2.0      9.870683
7   2022      HA   5640   6.884220    -2.0      4.799349
8   2022      MQ  21497  -1.326464   -10.0     -3.427143
9   2022      NK  16933   8.520168    -5.0      5.690738
10  2022      OH  18262  10.698828    -7.0      6.888362
11  2022      OO  58651   7.928475    -8.0      3.811479
12  2022      QX   7649  10.964571    -1.0      9.067830
13  2022      UA  42744   4.756270    -8.0      1.862575
14  2022      WN  90859   1.050331    -8.0     -0.397898
15  2022      YV   9920  11.159476    -7.0      6.374576
16  2022      YX  24315   3.306272    -8.0      1.016717

════════ Lan truyền trễ theo máy bay ════════

          prev_state       n  avg_dep_delay  dep_late15_rate
0       1_prev_early  320288       1.813187         0.090887
1      2_prev_ontime   75990       7.988209         0.178866
2   3_prev_late15_44   50151      20.771550         0.459891
3  4_prev_late45plus   43407      58.644758         0.633654

════════ BẰNG CHỨNG KỸ THUẬT SPARK ════════

26/10/28 08:44:10 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.
26/10/28 08:44:11 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

evidence_pruning → {"scan_partitions_no_filter": 329, "scan_partitions_with_filter": 7, "partition_filters": ["PartitionFilters: [isnotnull(year#358404), isnotnull(month#358406), (year#358404 = 2022), (month#358406 = 1)]"]}
evidence_joins → {"broadcast": {"rows": 21477, "seconds": 0.37, "strategy": "BroadcastHashJoin"}, "merge": {"rows": 21477, "seconds": 0.55, "strategy": "SortMergeJoin"}, "same_rowcount": true}

26/10/28 08:44:13 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.
26/10/28 08:44:16 WARN CacheManager: Asked to cache already cached data.

evidence_cache → {"no_cache_s": 2.21, "cache_fill_s": 0.12, "cached_3_runs_s": 1.38, "speedup_x": 1.6}

evidence_bucketing → {"exchange_plain": 2, "exchange_bucketed": 0, "plain_s": 2.21, "bucketed_s": 0.52}

26/10/28 08:44:30 WARN DataSource: [COLUMN_ALREADY_EXISTS] The column `month` already exists. Consider to choose another name or rename the existing column.

evidence_optimization → {"native_filter": {"late_flights": 97052, "seconds": 1.77, "pushed_filters": ["PushedFilters: [IsNotNull(ARR_DELAY), GreaterThanOrEqual(ARR_DELAY,15.0)]"]}, "udf_filter": {"late_flights": 97052, "seconds": 1.71, "pushed_filters": []}, "same_result": true}

Plan chi tiết đã lưu trong: /opt/spark_jobs/evidence